#the working directory
workdir: .

#directory where all outputs of the pipeline will be written
outdir: outputs

#nucleotide length of the cis regions to be targeted by the pipeline
cis_region: 5000

target_genome:
  annotation: inputs/ceratitis/GCF_000347755.3_Ccap_2.1_genomic.gff
  sequences:  inputs/ceratitis/GCF_000347755.3_Ccap_2.1_genomic.fna

reference_genome:
  annotation: inputs/dmel_inputs/Drosophila_melanogaster.BDGP6.28.49.protein_coding.bed
  sequences:  inputs/dmel_inputs/Drosophila_melanogaster.BDGP6.28.dna.toplevel.fa

# genome_sequences:
#   hg38: data/Homo_sapiens.GRCh38.dna.primary_assembly_singleLine.fa
#
# genome_annotations:
#   annotation_file: data/Homo_sapiens.GRCh38.90.gff3

# GTRD_peaks:
#   forward_strand: data/hg38.downstream_forward_within10kb_noCTCF_PCGsonly.txt
#   reverse_strand: data/hg38.upstream_reverse_within10kb_noCTCF_PCGsonly.txt
#

#
# JASPAR_db:
#   species_specific: data/JASPAR/Jaspar_PSSMs_hsap_1.txt
#   all_motifs: data/JASPAR/JASPAR_core_meta.csv
#   sites_dir: /ei/workarea/group-eg/project_cichlids/data/motifs/extrapolation/JASPAR2018/sites/
